table_name: testdaten
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
catalog: analyse
schema: public
sql: null
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 05a7e1bf-2e21-46ee-a0d2-36f9ede389fc
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: PVALUE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: VALUE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: AVG
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: MAX
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: MIN
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: SUM
  verbose_name: null
  is_dttm: false
  is_active: true
  type: DOUBLE PRECISION
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: STATE_ACQ
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: VALUEDATE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: MAXDATE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: STATE_VAL
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: STATE_COR
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: ENTRYDATE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: MINDATE
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: COMP_LEVEL
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: MESS_ID
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: OFFSET
  verbose_name: null
  is_dttm: false
  is_active: true
  type: INTEGER
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: VERSION
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: TEXT
  verbose_name: null
  is_dttm: false
  is_active: true
  type: TEXT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: e7adadf1-982d-4b39-b954-0ca0bb3792a0
