apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: airflow-operator
    meta.helm.sh/release-namespace: stackable-operators
  creationTimestamp: "2025-06-02T16:19:30Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: airflow-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: airflow-operator
    app.kubernetes.io/version: 0.0.0-dev
    helm.sh/chart: airflow-operator-0.0.0-dev
    stackable.tech/vendor: Stackable
  name: airflow-operator-deployment
  namespace: stackable-operators
  resourceVersion: "1990929"
  uid: fcc4660a-cb73-4162-a3fd-d8c3866d0335
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: airflow-operator
      app.kubernetes.io/name: airflow-operator
      stackable.tech/vendor: Stackable
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 76929aa7f1364f004fdd4f0fd0d26026fd97f21b5e9947d97ebca1af13da4aa4
        internal.stackable.tech/image: oci.stackable.tech/sdp/airflow-operator:0.0.0-dev
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: airflow-operator
        app.kubernetes.io/name: airflow-operator
        stackable.tech/vendor: Stackable
    spec:
      containers:
      - env:
        - name: OPERATOR_IMAGE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations['internal.stackable.tech/image']
        image: oci.stackable.tech/sdp/airflow-operator:0.0.0-dev
        imagePullPolicy: IfNotPresent
        name: airflow-operator
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/stackable/airflow-operator/config-spec
          name: config-spec
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: airflow-operator-serviceaccount
      serviceAccountName: airflow-operator-serviceaccount
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: airflow-operator-configmap
        name: config-spec
status:
  conditions:
  - lastTransitionTime: "2025-06-02T16:19:30Z"
    lastUpdateTime: "2025-06-02T16:19:36Z"
    message: ReplicaSet "airflow-operator-deployment-5877b447b7" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-14T16:34:24Z"
    lastUpdateTime: "2025-07-14T16:34:24Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
