apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: 10.0.161.192
      port: 8443
      rootPath: /realms/demo
      tls:
        verification:
          server:
            caCert:
              secretClass: keycloak-ca       #  <-- DARAUF zeigt Superset
