# authclass-keycloak-superset.yaml
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak-demo
spec:
  # OIDC-Konfiguration muss – laut Eurem CRD – direkt unter spec.oidc stehen.
  oidc:
    hostname: https://10.0.161.192
    port: 8443
    rootPath: /realms/demo
    principalClaim: preferred_username
    providerHint: Keycloak
    scopes:
      - openid
      - profile
      - email
    # Secret mit Euren Keycloak-Client-Daten (client_id + client_secret)
    clientCredentialsSecret: superset-oidc-client
