apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: 10.0.161.192
      port: 8443
      rootPath: /realms/master
      scopes:
        - email
        - openid
        - profile
      principalClaim: preferred_username
      providerHint: Keycloak
      clientId: superset
      tls:
        verification:
          server:
            caCert:
              webPki: {}
