apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak-demo
spec:
  provider:
    oidc:
      hostname: https://10.0.161.192
      port: 8443
      rootPath: /realms/demo
      principalClaim: preferred_username
      providerHint: Keycloak
      scopes:
        - openid
        - profile
        - email
      tls:
        none: {}
