apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: 10.0.161.192
      port: 8443
      rootPath: /realms/master
      scopes:
        - email
        - openid
        - profile
      principalClaim: preferred_username
      providerHint: Keycloak
      tls:
        verification:
          server:
            caCert:
              webPki: {}
      credentials:
        clientIdKey: client_id
        clientSecretKey: client_secret
        secret:
          name: superset-client-secret
          namespace: default
