apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: 10.0.156.237
      port: 8443
      rootPath: /realms/mm-stackable
      scopes:
        - email
        - openid
        - profile
      principalClaim: preferred_username
      providerHint: Keycloak
      tls:
        verification:
           server:
            caCert:
              secretClass: keycloak-ca   # <- genau dieser Name
