apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: 10.0.161.192 # Der Hostname deines Keycloak-Servers (z.B. keycloak.example.com)
      port: 8443 # Der Port, auf dem Keycloak läuft
      rootPath: /realms/demo # Der Realm-Pfad in Keycloak
      scopes: # Die benötigten Scopes
        - openid
        - profile
        - email
      principalClaim: preferred_username # Das Feld im UserInfo-Endpoint, das als Benutzername verwendet wird
      tls:
        verification:
          none: {} # Um die Server-Zertifikatsverifizierung zu deaktivieren (entspricht insecure: true)
