# file: authentication-class-http.yaml
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: 10.0.161.192     # unverändert
      port: 80                   # <--  **neu**  (Service oder NodePort für 8080)
      rootPath: /realms/demo
      scopes:
        - openid
        - profile
        - email
      principalClaim: preferred_username
      providerHint: Keycloak
      tls:                       # bei HTTP wird TLS ignoriert – trotzdem Feld nötig
        verification:
          none: {}               # <--  **neu**
