# keycloak-ca-secretclass.yaml
apiVersion: secret.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: keycloak-ca                 # beliebiger Name, hier = Secret-Name
spec:
  provider:
    kubernetesSecret:               # <-- Verweis auf bestehendes Secret
      name: keycloak-ca
      namespace: default
