apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak          # exakt wie dein Deployment heißt
  namespace: default      # ggf. anpassen
spec:
  template:
    spec:
      # ----- Secret als Volume einhängen -----
      volumes:
        - name: https
          secret:
            secretName: keycloak-https   # Secret, das du eben angelegt hast

      # ----- Container erweitern -----
      containers:
        - name: keycloak                # exakt Container-Name
          volumeMounts:
            - name: https
              mountPath: /etc/x509/https
          env:
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /etc/x509/https/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /etc/x509/https/tls.key
