--
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  type: LoadBalancer
  loadBalancerIP: 135.220.40.252  # << DEINE reservierte statische IP
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: keycloak
