---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm-config
stringData:
  realm.json: |
    {
      "realm": "mm-stackable",
      "enabled": true,
      "clients": [
        {
          "clientId": "jupyterhub",
          "enabled": true,
          "protocol": "openid-connect",
          "clientAuthenticatorType": "client-secret",
          "secret": "jupyterhubjupyterhub",
          "redirectUris": [ "http://135.220.40.252/hub/oauth_callback" ],
          "webOrigins": [ "http://135.220.40.252" ],
          "standardFlowEnabled": true
        }
      ],
      "users": [
        {
          "username": "isla.williams",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Isla",
          "lastName": "Williams",
          "email": "isla.williams@knab.com",
          "credentials": [
            {
              "type": "password",
              "value": "changeme"
            }
          ]
        },
        {
          "username": "daniel.king",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Daniel",
          "lastName": "King",
          "email": "daniel.king@knab.com",
          "credentials": [
            {
              "type": "password",
              "value": "changeme"
            }
          ]
        }
      ]
    }
