--
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      nodePort: 31093  # Fester Port für internen Zugriff
      name: https
  selector:
    app: keycloak

