# keycloak-ca-secretclass.yaml
apiVersion: secrets.stackable.tech/v1alpha1   #  <-- Plural + v1alpha1
kind: SecretClass
metadata:
  name: keycloak-ca
spec:
  backend:
    k8sSearch:                # wir “suchen” ein vorhandenes Secret
      searchNamespace:
        name: default         # dort liegt keycloak-ca
