---
releaseName: minio
name: minio
repo:
  name: minio
  url: https://charts.min.io/
version: 5.4.0
options:
  additionalLabels:
    stackable.tech/vendor: Stackable
  podLabels:
    stackable.tech/vendor: Stackable
  rootUser: admin
  rootPassword: {{ minioAdminPassword }}
  mode: standalone
  persistence:
    size: 10Gi
  buckets:
    - name: demo
      policy: none
  resources:
    requests:
      cpu: 1
      memory: 2Gi
  service:
    type: ClusterIP
    port: 9000
  consoleService:
    type: ClusterIP
    port: 9001
  consoleArgs:
    - --console-address
    - ":9001"
