---
releaseName: minio
name: minio
repo:
  name: minio
  url: https://charts.min.io/
version: 5.4.0 # RELEASE.2024-12-18T13-15-44Z
options:
  additionalLabels:
    stackable.tech/vendor: Stackable
  podLabels:
    stackable.tech/vendor: Stackable
  rootUser: admin
  rootPassword: adminadmin
  mode: standalone
  persistence:
    size: 10Gi
  buckets:
    - name: demo
      policy: none # Für Demos erlaubt öffentlicher Zugriff, für Produktion später z. B. auf "none" ändern
  resources:
    requests:
      cpu: 1
      memory: 2Gi
  service:
    type: NodePort
    nodePort: 30090      # <- S3 API erreichbar unter <node-ip>:30090
  consoleService:
    type: NodePort
    nodePort: 30091      # <- Web-Konsole erreichbar unter <node-ip>:30091
