apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-spark-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 1Gi
