apiVersion: v1
kind: Service
metadata:
  name: spark-connect
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: spark
    app.kubernetes.io/instance: spark-connect
  ports:
    - name: spark-connect
      port: 15002
      targetPort: 15002
  type: ClusterIP
