apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-connect-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["spark.stackable.tech"]
    resources: ["sparkconnectservers", "sparkapplications"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
