---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-connect-log-config
data:
  log4j2.properties: |-
    appenders = CONSOLE

    appender.CONSOLE.type = Console
    appender.CONSOLE.name = CONSOLE
    appender.CONSOLE.target = SYSTEM_ERR
    appender.CONSOLE.layout.type = PatternLayout
    appender.CONSOLE.layout.pattern = %d{ISO8601} %p [%t] %c - %m%n
    appender.CONSOLE.filter.threshold.type = ThresholdFilter
    appender.CONSOLE.filter.threshold.level = DEBUG

    rootLogger.level=INFO
    rootLogger.appenderRefs = CONSOLE
    rootLogger.appenderRef.CONSOLE.ref = CONSOLE

---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkConnectServer
metadata:
  name: spark-connect
  labels:
    stackable.tech/vendor: Stackable
    stackable.tech/stack: mm-stack
    stackable.tech/demo: mm-demo
spec:
  image:
    custom: oci.stackable.tech/stackable/spark-connect-client:3.5.5-stackable25.3.0
    productVersion: 3.5.5
    pullPolicy: IfNotPresent

  server:
    configOverrides:
      spark-defaults.conf:
        spark.driver.memory: "1g"
        spark.jars.ivy: "/tmp/ivy2"
    podOverrides:
      spec:
        serviceAccountName: spark
    config:
      resources:
        memory:
          limit: "1.2Gi"
      logging:
        enableVectorAgent: false
        containers:
          spark:
            custom:
              configMap: spark-connect-log-config

  executor:
    configOverrides:
      spark-defaults.conf:
        spark.executor.instances: "1"
        spark.executor.cores: "0.25"
        spark.executor.memory: "400m"
        spark.executor.memoryOverhead: "100m"
    config:
      resources:
        memory:
          limit: "512Mi"
      logging:
        enableVectorAgent: false
        containers:
          spark:
            custom:
              configMap: spark-connect-log-config
