---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: {{ supersetAdminPassword }}
  connections.secretKey: {{ supersetSecretKey }}
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset

  # OAuth für Keycloak
  AUTH_TYPE: "AUTH_OAUTH"
  OAUTH_PROVIDERS: |
    [{
      'name':'keycloak',
      'icon':'fa-address-card',
      'token_key':'access_token',
      'remote_app': {
        'client_id':'superset',
        'client_secret':'{{ keycloakSupersetClientSecret }}',
        'api_base_url':'https://keycloak:8443/realms/demo/protocol/openid-connect/',
        'client_kwargs': {
          'scope': 'openid profile email'
        },
        'access_token_url':'https://keycloak:8443/realms/demo/protocol/openid-connect/token',
        'authorize_url':'https://keycloak:8443/realms/demo/protocol/openid-connect/auth'
      }
    }]
