apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 4.1.2
  clusterConfig:
    listenerClass: external-unstable
    credentialsSecret: superset-credentials
    mapboxSecret: superset-mapbox-api-key
    authentication:
      - authenticationClass: keycloak
        oidc:
          clientCredentialsSecret: superset-keycloak-client
        userRegistrationRole: Gamma_extended
  nodes:
    worker: # Hier kommt der Rollenname
      roleGroups:
        default: # Hier kommt der Name der RoleGroup
          replicas: 1
  podOverrides:
    spec:
      initContainers:
        - name: wait-for-setup-db-job
          image: oci.stackable.tech/sdp/testing-tools:0.2.0-stackable0.0.0-dev
          command:
            - bash
            - -c
            - |
              kubectl wait --for=condition=complete job/setup-db-job
