apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  clusterConfig:
    authentication:
      - authenticationClass: keycloak
        oidc:
          clientCredentialsSecret: superset-keycloak-client
          extraScopes:
            - groups
    credentialsSecret: superset-credentials
  image:
    productVersion: "2.1"
  nodes:
    worker: # 'worker' ist der Rollenname
      roleGroups:
        default: {} # 'default' ist der Name der RoleGroup innerhalb der 'worker'-Rolle
