apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  clusterConfig:
    authentication:
      - authenticationClass: keycloak
        oidc:
          clientCredentialsSecret: superset-keycloak-client # Der Name des Secrets mit client_id und client_secret
          extraScopes: # Optionale zusätzliche Scopes
            - groups
    credentialsSecret: superset-credentials # Secret für Admin-User und DB-Verbindung
  image:
    productVersion: "2.1" # Beispiel Superset Version
  nodes:
    worker:
      roleGroups:
        default: {}
