apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: superset-oidc-client
spec:
  backend:
    inline:
      type: opaque
      data:
        client_id: superset
        client_secret: dein-geheimes-client-secret
