apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
  labels:
    app: tailscale-subnet-router
spec:
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      hostNetwork: true
      serviceAccountName: tailscale-svc-account
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: ts-state
          hostPath:
            path: /var/lib/tailscale
            type: DirectoryOrCreate
        - name: ts-run
          emptyDir: {}
      containers:
        - name: tailscaled
          image: ghcr.io/tailscale/tailscale:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
          command:
            - /bin/sh
            - -c
            - |
                exec tailscaled \
                  --state=/var/lib/tailscale/tailscaled.state \
                  --tun=userspace-networking
          volumeMounts:
            - name: ts-state
              mountPath: /var/lib/tailscale
            - name: ts-run
              mountPath: /var/run/tailscale

        - name: tailscale-up
          image: ghcr.io/tailscale/tailscale:latest
          imagePullPolicy: Always
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_ROUTES
              value: 10.0.0.0/16,10.244.0.0/16
          command:
            - /bin/sh
            - -c
            - |
                sleep 5
                tailscale up \
                  --authkey=${TS_AUTHKEY} \
                  --advertise-routes=${TS_ROUTES} \
                  --accept-dns=false
                echo "tailscale up done, keeping container alive ..."
                sleep infinity
          volumeMounts:
            - name: ts-state
              mountPath: /var/lib/tailscale
            - name: ts-run
              mountPath: /var/run/tailscale
